ADB:
- C:/CODE/main.nut /sdcard/
- com.emo_framework.examples/com.emo_framework.EmoActivity
- EmoFramework
- adb -d shell ps | grep com.emo_framework.examples | awk '{print $2}' | xargs adb
  shell kill
ANT:
- android update project --target 5 --path .
- ant debug install
File:
- C:/CODE/assets/creditscene.nut
- C:/CODE/assets/main.nut
- C:/CODE/assets/logoscene.nut
Project:
- C:/CODE/data/
- C:/CODE/assets/
Recent:
- C:\CODE\main.nut
Setting:
  fontname: Courier New
  fontsize: 10
  iconsize: 16
  styleindex: 8
  thresh: 1
  workspace: C:/CODE/
Style: 0
